version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"
    volumes:
      - esdata6:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      main:
        aliases:
          - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    volumes:
      - logstash_pipeline:/usr/share/logstash/pipeline/
      - logstash_data:/usr/share/data
    networks:
      main:
        aliases:
          - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - "5601:5601"
    networks:
      main:
        aliases:
          - kibana

networks:
  main:

volumes:
  esdata6:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/mounts/esdata6
  logstash_pipeline:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/logstash
  logstash_data:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/mounts/logstash_data
