version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      main:
        aliases:
          - mongodb

  elasticsearch:
    image: elasticsearch:2-alpine
    ports:
      - "9200:9200"
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      main:
        aliases:
          - esdb

  fuzzy_get_api:
    build:
      context: ./fetch-api
      dockerfile: Dockerfile
    networks:
      main:
        aliases:
          - fuzzy_api
    ports:
      - "5000:5000"

  es_connector:
    build:
      context: ./connector
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - esconnector2:/usr/src/app
    networks:
      main:
        aliases:
          - es_mongo_connector

networks:
  main:

volumes:
  mongodata:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/mounts/data
  esdata2:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/mounts/esdata2
  esconnector2:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/connector
