version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"
    volumes:
      - esdata6:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      main:
        aliases:
          - elasticsearch

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    ports:
      - "5044:5044"
    networks:
      main:
        aliases:
          - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - "5601:5601"
    networks:
      main:
        aliases:
          - kibana

  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    volumes:
      - filebeat_data:/usr/src/data/
    networks:
      main:
        aliases:
          - filebeat

networks:
  main:

volumes:
  esdata6:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/mounts/esdata6
  filebeat_data:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tanmai/Documents/fuzzy-address-matching/mounts/filebeat_data
